# Generated by Django 5.2 on 2025-05-05 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_rename_buyer_column"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="message",
            table="chat_message",
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='participant2',
            new_name='seller',
        ),
    ]
