# Generated by Django 5.2 on 2025-05-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_message_is_read"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversation",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "對話",
                "verbose_name_plural": "對話紀錄",
            },
        ),
        migrations.AddField(
            model_name="conversation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="is_read",
            field=models.BooleanField(default=False, verbose_name="是否已讀"),
        ),
    ]
