# Generated by Django 5.2 on 2025-04-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mywebsite", "0004_auto_20250421_1143"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
