# Generated by Django 5.2 on 2025-04-21 17:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mywebsite", "0005_alter_category_id_alter_post_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="favorites",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorite_posts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="收藏的使用者",
            ),
        ),
    ]
