# Generated by Django 5.2 on 2025-04-23 13:39

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mywebsite", "0007_post_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_reserved",
            field=models.BooleanField(default=False, verbose_name="已被預約"),
        ),
        migrations.AddField(
            model_name="post",
            name="is_sold",
            field=models.BooleanField(default=False, verbose_name="已售出"),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reserved_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="預約時間"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="mywebsite.post",
                        verbose_name="預約商品",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="預約者",
                    ),
                ),
            ],
            options={
                "verbose_name": "預約紀錄",
                "verbose_name_plural": "預約紀錄",
                "unique_together": {("product", "user")},
            },
        ),
    ]
