# Generated by Django 5.0 on 2025-04-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0010_post_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
