# Generated by Django 5.0 on 2025-04-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0012_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
