# Generated by Django 5.2 on 2025-04-27 18:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mywebsite", "0016_alter_post_buyer_alter_post_favorites_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="favorite_posts",
            field=models.ManyToManyField(
                related_name="favorited_by_users", to="mywebsite.post"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="favorites",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorited_posts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="收藏的使用者",
            ),
        ),
    ]
