# Generated by Django 5.2 on 2025-04-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0017_customuser_favorite_posts_alter_post_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='purchase_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='購買時間'),
        ),
    ]
