# Generated by Django 5.2 on 2025-04-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mywebsite", "0018_post_purchase_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender", models.CharField(max_length=150)),
                ("content", models.TextField()),
                ("seller_id", models.IntegerField()),
                ("product_id", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
