# Generated by Django 5.2 on 2025-05-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mywebsite", "0019_chatmessage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "通知",
                "verbose_name_plural": "通知列表",
            },
        ),
        migrations.AddField(
            model_name="notification",
            name="link",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="相關連結"
            ),
        ),
    ]
