# Generated by Django 5.2 on 2025-05-19 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mywebsite", "0020_alter_notification_options_notification_link"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={},
        ),
        migrations.RemoveField(
            model_name="notification",
            name="link",
        ),
        migrations.RemoveField(
            model_name="post",
            name="favorites",
        ),
    ]
